"""Email Processing Pipeline"""

from sqlalchemy.orm import Session
from app.models.email import Email
from app.models.analysis import EmailAnalysis
from app.models.decision import Decision
from app.models.action import SuggestedAction

from app.services.ai_engine.intent_detector import IntentDetector
from app.services.ai_engine.entity_extractor import EntityExtractor
from app.services.ai_engine.summarizer import EmailSummarizer
from app.services.ai_engine.priority_scorer import PriorityScorer
import logging

logger = logging.getLogger(__name__)


class EmailProcessor:
    """Complete email processing pipeline"""
    
    def __init__(self, db: Session):
        self.db = db
        self.intent_detector = IntentDetector()
        self.entity_extractor = EntityExtractor()
        self.summarizer = EmailSummarizer()
        self.priority_scorer = PriorityScorer()
    
    def process_email(self, email_id: str) -> dict:
        """Process email through AI pipeline"""
        email = self.db.query(Email).filter_by(id=email_id).first()
        if not email:
            return {"error": "Email not found"}
        
        try:
            # AI Analysis
            intent_result = self.intent_detector.detect_intent(
                email.subject, email.body
            )
            
            entities = self.entity_extractor.extract_entities(email.body)
            summary = self.summarizer.summarize(email.body)
            priority_result = self.priority_scorer.score_priority(
                email.subject, email.body, email.sender
            )
            
            # Store analysis
            analysis = EmailAnalysis(
                email_id=email.id,
                intent=intent_result.get('intent', 'general'),
                priority=priority_result.get('priority', 'medium'),
                confidence=intent_result.get('confidence', 0.5),
                summary=summary,
                entities=entities
            )
            self.db.add(analysis)
            self.db.commit()
            
            # Create decision
            decision = Decision(
                email_id=email.id,
                decision_type=intent_result.get('intent', 'general'),
                rationale=intent_result.get('reasoning', 'AI analysis')
            )
            self.db.add(decision)
            self.db.commit()
            self.db.refresh(decision)
            
            # Create suggested actions
            actions = self._generate_actions(decision, intent_result, entities)
            for action_data in actions:
                action = SuggestedAction(
                    decision_id=decision.id,
                    action_type=action_data['type'],
                    payload=action_data['payload'],
                    status='pending'
                )
                self.db.add(action)
            
            self.db.commit()
            
            return {
                "email_id": email.id,
                "analysis_id": analysis.id,
                "decision_id": decision.id,
                "intent": intent_result.get('intent'),
                "priority": priority_result.get('priority')
            }
        
        except Exception as e:
            logger.error(f"Error processing email: {e}")
            self.db.rollback()
            return {"error": str(e)}
    
    def _generate_actions(self, decision, intent_result, entities) -> list:
        """Generate action suggestions based on intent"""
        actions = []
        
        intent = intent_result.get('intent', 'general')
        
        if intent == 'meeting_request':
            actions.append({
                'type': 'create_calendar_event',
                'payload': {
                    'suggested_date': entities.get('dates', ['TBD'])[0] if entities.get('dates') else 'TBD',
                    'suggested_time': entities.get('times', ['TBD'])[0] if entities.get('times') else 'TBD'
                }
            })
        
        if intent in ['question', 'task_assignment']:
            actions.append({
                'type': 'generate_reply',
                'payload': {
                    'tone': 'professional',
                    'draft': 'Reply generated by AI'
                }
            })
        
        return actions